server:
  port: 8083

spring:
  application:
    name: media-service
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  upload:
    dir: uploads
  jwt:
    secret: 9A4f7b2c8E1d5F6aB3e0D9c7F8a2B1e5D6c4A3b8F0E7d9C1a5B2f6E3d4A8c0B1
